name: Publish

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/publish.yml"
            - "scripts/dnsconfig.js"

concurrency:
    group: ${{ github.ref }}-publish
    cancel-in-progress: false

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json
            - name: Publish
              uses: is-cool-me/dnscontrol-action@v4.11.0
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              with:
                  args: push
                  config_file: "scripts/dnsconfig.js"